version: "3.9"
services:
  php:
    build: .
    restart: never
    volumes: 
      - ./:/var/www/html
    ports: 
      - 8080:80
    links:
      - mariadb
  
  mariadb:
    image: "mariadb:latest"
    restart: never
    ports: 
      - 3306:3306
    volumes:
      - ./db/riddler.sql
    environment:
      MYSQL_DATABASE: riddler
      MYSQL_ROOT_PASSWORD: "root"
  
  myadmin:
    depends_on:
      - mariadb
    image: "phpmyadmin:latest"
    restart: never
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mariadb